// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjzluevleijvokaxdmni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhqemx1ZXZsZWlqdm9rYXhkbW5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1MTA0NTIsImV4cCI6MjA1NDA4NjQ1Mn0.FgIKTwdfvsDePdrnnwr81SxgmHj3dQpcZnx7WOmHVgc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);